### ISSUE TITLE
Toontown Rewritten Content Pack Texture Cap

### ISSUE THREAD

**Issue by weirdwacko** [Toontown-Texture-Restoration/Toontown-Texture-Restoration#15]
### **Issue With Using 1024x Textures**

Prior to a recent update, Toontown Rewritten used to cap textures on the square resolution 1024x1024. However as of [December 29th of 2019](https://twitter.com/Toontown/status/1211168581909528576) in order to fix an issue with some users not being able to get in game, Toontown Rewritten made the cap 512x512 for Content Packs.

For any packs that have any textures above 512 resolution, the game has to downscale textures in real time. Panda3D's down-scaling algorithm has a big issue in accomplishing this however. Performance issues are common in HD texture packs as result of this. Causing heavy stuttering.

### **What's the solution?**

Two solutions come to mind, the less preferable one being making all of our textures in 512x512, but this comes at the cost of making it worse for usage by other projects. I do not recommend this solution personally.

Another solution I came up with, which while more strenuous, is better in the long run, is having an alternate Toontown Rewritten content pack which keeps all textures at 512x512 resolution at the max. I think this is the best solution in my eyes, but I'd like to hear everyone else's thoughts on this subject.

**Comment by ghost** [comment]
Solution 2 is likely the best idea. However, to do this, you would likely want to resize from the uncompressed palletes, and, the likelyhood of png versions of all of these pallets existing (thats actual proper lossless pngs, not jpeg to png conversions), seems a bit slim, to me.

If, however, this can be done, a separate branch should be made, imo.

**Comment by ghost** [comment]
OK, so, assuming I can get my hands on proper lossless copies of all palletes made, thus far, I could do the following:

1. Resize them all to 512x512, likely with an ImageMagick Script.

2. Use The Spoofer to split the alpha and main image, of all the png's (please let there be a batch option), to create usable JPEG and RGB files for the game.

3. Push it to a separate branch, called TTR, so the full res pallates can still be made, and downsized versions, just for TTR, can also exist.

**Comment by DarthMDev** [comment]
Come on TTR it’s 2020 -.- make the cap an optional in game setting so people can have a nice experience

**Comment by Wizeguy400** [comment]
Do #2 please

**Comment by loonaticx** [comment]
This can ultimately be resolved with creating a new branch designed for TTR compatibility. I would prefer if any sort of extra content, such as artificial upscaling and sever-related limitations to be worked on later.

**Comment by loonaticx** [comment]
To resolve this issue, I went ahead and created a new branch labeled "TTR-Compatibility". It is synchronized to the master branch, so there is no need to create multiple pull requests. This branch should only be for assets that are specialized FOR Toontown Rewritten. This includes assets that weren't in the original TTO phases (ex: any palette with _rerigged is a TTR-exclusive palette) along with any downscaled versions.
