### ISSUE TITLE
Possible Source for Missing Assets

### ISSUE THREAD

**Issue by ghost** [Toontown-Texture-Restoration/Toontown-Texture-Restoration#20]
As you probably know by now, Spotify does not contain all the assets from the final days of Toontown Online.

For missing assets, I think we can use something I developed myself, not too long ago. It's a content pack called Reinvigorated, which upscales all textures by 4x their original size. We can use this to get missing assets, and TTR assets. The Toolkit in particular that I included with the post, contains the original raw png upscales, and just the textures with dejpegging. If anyone wants to sort through these assets, and get the assets that are missing, you are free to do so.

Link to the pack and toolkit is here: [http://www.mmocentralforums.com/forums/showthread.php?t=377663](url)

**Comment by loonaticx** [comment]
I do not recommend integrating this content pack with the master branch of this repo. It can be merged into this project on a different branch only.

**Comment by ghost** [comment]
Alright. I merely suggested it, due to the fact that it has assets pandora/spotify doesnt.
