### ISSUE TITLE
Cobblestone texture not alliging properly

### ISSUE THREAD

**Issue by Wizeguy400** [Toontown-Texture-Restoration/Toontown-Texture-Restoration#30]
![alligning](https://user-images.githubusercontent.com/25600996/87388224-63d3f400-c572-11ea-8bbf-7861d1168f3b.png)

**Comment by ghost** [comment]
This looks more like an UV issue. This cannot be fixed, unless you modify the model itself.

**Comment by Wizeguy400** [comment]
That's a shame
